# Generated by Django 4.0.5 on 2022-07-08 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, default='/gallery/default.jpg', null=True, upload_to='gallery')),
                ('caption', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='studentx', max_length=10)),
                ('username', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('program', models.CharField(max_length=9)),
                ('institution', models.CharField(max_length=15)),
                ('contact', models.IntegerField()),
                ('field_of_interest', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=7)),
                ('password', models.CharField(max_length=20)),
                ('placement_letter', models.CharField(max_length=2089)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp', models.ImageField(blank=True, default='/profiles/default.jpg', null=True, upload_to='profiles')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
