# Generated by Django 4.0.5 on 2022-07-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stratcom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact',
            new_name='number',
        ),
    ]
