# Generated by Django 4.0.5 on 2022-07-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratcom', '0002_rename_contact_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
